os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

addons:
  apt:
    packages:
    - sshpass
    
script:
- docker build -t otakushelter/accounts:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Account.Web/Dockerfile .
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/accounts:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
    "cd /root/OtakuShelter.Infrastructure/src && \
    ansible-playbook deploy.yml \
    -e \"\
    otakushelter_hosts=accounts \
    otakushelter_port=4002 \
    otakushelter_image=otakushelter/accounts \
    otakushelter_server_name=account.otaku-shelter.ru \
    otakushelter_build_number=$TRAVIS_BUILD_NUMBER \
    otakushelter_database_password=$OTAKUSHELTER_DATABASE_PASSWORD \
    otakushelter_rabbitmq_password=$OTAKUSHELTER_RABBITMQ_PASSWORD \
    otakushelter_secret=$OTAKUSHELTER_SECRET\" \
    -i inventories/staging"