database:
  host: database.otaku-shelter.ru
  port: 5432
  database: account
  userid: account
  migrationstable: migrations
  
secret: secretsecretsecretsecretsecret
issuer: otakushelter.issuer
audience: otakushelter.audience
maxtokenscount: 10