database:
  host: 192.168.1.99
  port: 4001
  database: otakushelter
  userid: otakushelter
  password: otakushelter
  migrationstable: migrations
  
secret: secretsecretsecretsecretsecret
issuer: otakushelter.issuer
audience: otakushelter.audience